/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EnergyCheckUtils */

#ifndef _Included_edu_binghamton_vpc_JRapl
#define _Included_edu_binghamton_vpc_JRapl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EnergyCheckUtils
 * Method:    ProfileInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_binghamton_vpc_JRapl_ProfileInit
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    GetSocketNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_binghamton_vpc_JRapl_GetSocketNum
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    EnergyStatCheck
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_binghamton_vpc_JRapl_EnergyStatCheck
  (JNIEnv *, jclass);

/*
 * Class:     EnergyCheckUtils
 * Method:    ProfileDealloc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_JRapl_ProfileDealloc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
