/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_binghamton_vpc_PerfUtils */

#ifndef _Included_edu_binghamton_vpc_PerfUtils
#define _Included_edu_binghamton_vpc_PerfUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    get_energy
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_edu_binghamton_vpc_PerfUtils_get_1energy
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    timer_start_recording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_timer_1start_1recording
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    timer_read_counters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_timer_1read_1counters
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    start_recording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_start_1recording
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    stop_recording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_stop_1recording
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    register_thread_stat
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_register_1thread_1stat
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    read_counters_reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_read_1counters_1reset
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    init_papi_lib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_init_1papi_1lib
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    set_energy_enabled
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_set_1energy_1enabled
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    timer_init_events
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_timer_1init_1events
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    init_papi
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_init_1papi
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    init_event_names
 * Signature: (I[[BI)V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_init_1event_1names
  (JNIEnv *, jclass, jint, jobjectArray, jint);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    print_thread_counters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_print_1thread_1counters
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    print_energy_counters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_print_1energy_1counters
  (JNIEnv *, jclass);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    print_energy_counters_expid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_print_1energy_1counters_1expid
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    get_timestamp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_binghamton_vpc_PerfUtils_get_1timestamp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
