/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h>
#include <time.h>
#include "PerfUtils.h"
#include "perf_utils.h"
/* Header for class PerfUtils */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PerfUtils
 * Method:    start_recording
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_start_1recording(JNIEnv *env, jclass cls) {
	start_recording();
 }

/*
 * Class:     PerfUtils
 * Method:    stop_recording
 * Signature: ()V
 */
JNIEXPORT void JNICALL JNICALL Java_edu_binghamton_vpc_PerfUtils_stop_1recording
  (JNIEnv *env , jclass cls) {
	stop_recording();
  }


/*
 * Class:     PerfUtils
 * Method:    sysPerfStopRecording
 * Signature: ()V
 */
// JNIEXPORT void JNICALL Java_PerfUtils_sysPerfStopRecording
//   (JNIEnv *env, jclass cls) {
// 	sysPerfStopRecording();
//   }

/*
 * Class:     PerfUtils
 * Method:    register_thread_stat
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_register_1thread_1stat
  (JNIEnv *env , jclass cls) {
	register_thread_stat();
  }

/*
 * Class:     PerfUtils
 * Method:    read_counters_reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_read_1counters_1reset
  (JNIEnv *env , jclass cls) {
	read_counters_reset();
  }

/*
 * Class:     PerfUtils
 * Method:    sysReadCountersReset
 * Signature: ()V
 */
// JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_sysReadCountersReset
//   (JNIEnv *env, jclass cls) {
// 	sysReadCountersReset();
//   }


/*
 * Class:     PerfUtils
 * Method:    init_papi_lib
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_init_1papi_1lib
  (JNIEnv *env, jclass cls) {
	init_papi_lib();
  }

/*
 * Class:     PerfUtils
 * Method:    set_energy_enabled
 * Signature: (I)V
 */
JNIEXPORT void JNICALL JNICALL Java_edu_binghamton_vpc_PerfUtils_set_1energy_1enabled
  (JNIEnv *env , jclass cls, jint flag) {
	set_energy_enabled(flag);
  }


/*
 * Class:     PerfUtils
 * Method:    init_event_names
 * Signature: (I[[BI)V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_init_1event_1names
  (JNIEnv *env, jclass cls, jint len, jobjectArray names, jint whch) {

	  char* readBuffer = (*env)->GetByteArrayElements(env, names, NULL);
	  init_event_names(len, names, whch);
  }


JNIEXPORT jdouble JNICALL Java_edu_binghamton_vpc_PerfUtils_get_1energy
  (JNIEnv *env, jclass cls) {
        return get_energy();
  }


JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_timer_1start_1recording
  (JNIEnv *env, jclass cls) {
	timer_start_recording();
  }

/*
 * Class:     edu_binghamton_vpc_PerfUtils
 * Method:    timer_read_counters
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_timer_1read_1counters
  (JNIEnv *env, jclass cls) {
	timer_read_counters_reset();
  }

char** strings_to_c(JNIEnv *env,jobjectArray array) {
	jsize len = (*env)->GetArrayLength(env,array);
	char** c_string_array = (char**) malloc(sizeof(char*)*len);

	for(int i=0; i<len;i++) {
        	jstring string = (jstring) (*env)->GetObjectArrayElement(env, array, i);
		c_string_array[i] = (*env)->GetStringUTFChars(env, string, NULL);
	}

	return c_string_array;
}




JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_init_1papi(JNIEnv *env, jclass cls, jobjectArray array) {
	char** names = strings_to_c(env, array);
	jsize len = (*env)->GetArrayLength(env, array);
	init_papi(len, names);

}


JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_timer_1init_1events(JNIEnv *env, jclass cls, jobjectArray array) {
	char** names = strings_to_c(env,array);
	jsize len = (*env)->GetArrayLength(env, array);
	timer_init_events(len, names);
}


JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_print_1thread_1counters
  (JNIEnv *env , jclass cls) {
	print_counters_g();
  }



JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_print_1energy_1counters
  (JNIEnv *env, jclass cls) {
	printf("Energy Counters *****************************************************************");
  	print_timer_counters();
 }

JNIEXPORT void JNICALL Java_edu_binghamton_vpc_PerfUtils_print_1energy_1counters_1expid
  (JNIEnv *env, jclass cls, jint expid) {
	  printf("Energy Countes ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
	  printf("Printing Energy Counters %d", expid);
  	  print_timer_counters_exp(expid);
}


JNIEXPORT jlong JNICALL Java_edu_binghamton_vpc_PerfUtils_get_1timestamp
  (JNIEnv *env, jclass cls) {
	  struct timespec ts;
	  clock_gettime(CLOCK_MONOTONIC,&ts);
	  long long total_time = (ts.tv_sec*1000000000) + ts.tv_nsec;
	  return total_time;

  }

#ifdef __cplusplus
}
#endif
